plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
# theme: jekyll-theme-minimal
# theme: jekyll-theme-dinky
# theme: jekyll-theme-slate
theme: jekyll-theme-minima
include:
  - out.md