contact:
- inCitation: true
  individual:
    email: matt.lemay@hakai.org
    name: Lemay, Matthew
    orcid: https://orcid.org/0000-0001-7051-0020
    position: Scientist
  organization:
    city: Campbell River
    country: Canada
    name: Hakai Institute
    ror: https://ror.org/02pry0c91
    url: https://www.hakai.org/
  roles:
  - custodian
  - owner
  - pointOfContact
  - distributor
- inCitation: true
  individual:
    email: rute.carvalho@hakai.org
    name: Clemente-Carvalho, Rute
    orcid: https://orcid.org/0000-0001-6922-9418
    position: Lab Manager
  organization:
    city: Campbell River
    country: Canada
    name: Hakai Institute
    ror: https://ror.org/02pry0c91
    url: https://www.hakai.org/
  roles:
  - coAuthor
- inCitation: true
  individual:
    email: evan.morien@hakai.org
    name: Morien, Evan
    orcid: https://orcid.org/0000-0001-9821-7002
  organization:
    city: Campbell River
    country: Canada
    name: Hakai Institute
    ror: https://ror.org/02pry0c91
    url: https://www.hakai.org/
  roles:
  - coAuthor
- inCitation: true
  individual:
    email: kristin.meagher@hakai.org
    name: Robinson, Kristin
    orcid: https://orcid.org/0000-0002-9500-1983
  organization:
    city: Campbell River
    country: Canada
    name: Hakai Institute
    ror: https://ror.org/02pry0c91
    url: https://www.hakai.org/
  roles:
  - coAuthor
- inCitation: true
  individual:
    email: carolyn.prentice@hakai.org
    name: Prentice, Carolyn
    orcid: https://orcid.org/0000-0002-9644-8496
  organization:
    city: Campbell River
    country: Canada
    name: Hakai Institute
    ror: https://ror.org/02pry0c91
    url: https://www.hakai.org/
  roles:
  - coAuthor
- inCitation: true
  individual:
    name: Savage, Rosie
  organization:
    city: Campbell River
    country: Canada
    name: Hakai Institute
    ror: https://ror.org/02pry0c91
    url: https://www.hakai.org/
  roles:
  - coAuthor
- inCitation: true
  individual:
    name: Millard-Martin, Ben
  organization:
    city: Montreal
    country: Canada
    name: McGill University
    ror: https://ror.org/01pxwe438
    url: https://www.mcgill.ca
  roles:
  - coAuthor
- inCitation: true
  individual:
    name: Hall, Kyle
  organization:
    city: Campbell River
    country: Canada
    name: Hakai Institute
    ror: https://ror.org/02pry0c91
    url: https://www.hakai.org/
  roles:
  - coAuthor
- inCitation: true
  individual:
    name: Sheridan, Kate
  roles:
  - coAuthor
- inCitation: true
  individual:
    name: Jeffery, Nick
  organization:
    city: Ottawa
    country: Canada
    name: Fisheries and Oceans Canada
    ror: https://ror.org/02qa1x782
    url: https://www.dfo-mpo.gc.ca
  roles:
  - coAuthor
- inCitation: true
  individual:
    name: Stanley, Ryan
  organization:
    city: Ottawa
    country: Canada
    name: Fisheries and Oceans Canada
    ror: https://ror.org/02qa1x782
    url: https://www.dfo-mpo.gc.ca
  roles:
  - coAuthor
- inCitation: true
  individual:
    name: Rubidge, Emily
    orcid: https://orcid.org/0000-0001-8997-1177
  organization:
    city: Ottawa
    country: Canada
    name: Fisheries and Oceans Canada
    ror: https://ror.org/02qa1x782
    url: https://www.dfo-mpo.gc.ca
  roles:
  - coAuthor
- inCitation: true
  individual:
    name: Sunday, Jennifer
    orcid: https://orcid.org/0000-0001-9372-040X
  organization:
    city: Montreal
    country: Canada
    name: McGill University
    ror: https://ror.org/01pxwe438
    url: https://www.mcgill.ca
  roles:
  - coAuthor
distribution:
- description:
    en: 'Raw Illumina Sequence Reads are accessioned at NCBI (BioProject: PRJNA1269473)'
    fr: 'Les lectures de séquences Illumina brutes sont accessibles au NCBI (BioProject :
      PRJNA1269473)'
    translations:
      fr:
        message: text translated using the Amazon translate service / texte traduit
          à l'aide du service de traduction Amazon
        verified: false
  name:
    en: 'Illumina Sequence Reads (BioProject: PRJNA1269473)'
    fr: 'Les lectures de séquences Illumina brutes sont accessibles au NCBI (BioProject :
      PRJNA1269473)'
    translations:
      fr:
        message: text translated using the Amazon translate service / texte traduit
          à l'aide du service de traduction Amazon
        verified: false
  url: https://www.ncbi.nlm.nih.gov/bioproject/1269473
- description:
    en: Attributes of each seawater sample collected for this research project.
    fr: Attributs de chaque échantillon d'eau de mer prélevé pour ce projet de recherche.
    translations:
      fr:
        message: text translated using the Amazon translate service / texte traduit
          à l'aide du service de traduction Amazon
        verified: false
  name:
    en: Sample Metadata
    fr: Exemples de métadonnées
    translations:
      fr:
        message: text translated using the Amazon translate service / texte traduit
          à l'aide du service de traduction Amazon
        verified: false
  url: https://drive.google.com/file/d/1HZwclPQWInj9PvzrLbWHrXX3Wfj0iJqa/view?usp=sharing
- description:
    en: Detailed methods for the collection, sequencing, and bioinformatic processing
      of samples used in this project.
    fr: Méthodes détaillées pour la collecte, le séquençage et le traitement bioinformatique
      des échantillons utilisés dans ce projet.
    translations:
      fr:
        message: text translated using the Amazon translate service / texte traduit
          à l'aide du service de traduction Amazon
        verified: false
  name:
    en: Methods
    fr: Méthodes
    translations:
      fr:
        message: text translated using the Amazon translate service / texte traduit
          à l'aide du service de traduction Amazon
        verified: false
  url: https://docs.google.com/document/d/1a4TWaYVssrhyoQZaYINJ9fhyyTtxMiomGHr1ORyDBU8/edit?usp=sharing
- description:
    en: Filtered, QC'ed and annotated ASV table generated from the COI amplicon sequence
      data
    fr: Tableau ASV filtré, QC et annoté généré à partir des données de séquence d'amplicons
      COI
    translations:
      fr:
        message: text translated using the Amazon translate service / texte traduit
          à l'aide du service de traduction Amazon
        verified: false
  name:
    en: ASV Table (COI)
    fr: Tableau ASV (COI)
    translations:
      fr:
        message: text translated using the Amazon translate service / texte traduit
          à l'aide du service de traduction Amazon
        verified: false
  url: https://drive.google.com/file/d/1Tw03bY62hk--hEvdLtAsc4_yRrIJGI27/view?usp=sharing
- description:
    en: Filtered, QC'ed and annotated ASV table generated from the 12S amplicon sequence
      data
    fr: Tableau ASV filtré, QC et annoté généré à partir des données de séquence d'amplicons
      12S
    translations:
      fr:
        message: text translated using the Amazon translate service / texte traduit
          à l'aide du service de traduction Amazon
        verified: false
  name:
    en: ASV Table (12S)
    fr: Tableau ASV (12S)
    translations:
      fr:
        message: text translated using the Amazon translate service / texte traduit
          à l'aide du service de traduction Amazon
        verified: false
  url: https://drive.google.com/file/d/1Mnr29_XJeSZsJ-jWtPCxizt37B7Wj4lB/view?usp=sharing
- description:
    en: This webpage provides additional information on Project Optimize, which is
      a collaboration between researchers from the McGill University, Fisheries and
      Oceans Canada, and the Hakai Institute
    fr: Cette page Web fournit des informations supplémentaires sur le projet Optimize,
      qui est une collaboration entre des chercheurs de l'Université McGill, de Pêches
      et Océans Canada et de l'Institut Hakai
    translations:
      fr:
        message: text translated using the Amazon translate service / texte traduit
          à l'aide du service de traduction Amazon
        verified: false
  name:
    en: Project Webpage
    fr: Page Web du projet
    translations:
      fr:
        message: text translated using the Amazon translate service / texte traduit
          à l'aide du service de traduction Amazon
        verified: false
  url: https://genomegapp.weebly.com
identification:
  abstract:
    en: This data package contains molecular resources derived from a large DNA-based
      survey of marine biodiversity carried out around Calvert Island, British Columbia,
      in 2021. During this survey we collected triplicate seawater samples from 208
      sites across a marine region roughly 100km2 in scale, focussed on nearshore
      habitats of kelp, seagrass, and rocky reefs. All samples were collected adjacent
      to the substrate using a niskin bottle, filtered using 0.22μm sterivex filters,
      and the resulting environmental DNA was used for amplicon sequencing to infer
      the communities of fish (12S rRNA gene) and invertebrates (COI) at each location.
      These data are part of a larger collaboration between researchers from McGill
      University, Fisheries and Oceans Canada, and the Hakai Institute, with the goal
      of optimizing the use of environmental DNA for monitoring Canada’s network of
      Marine Protected Areas.
    fr: Ce paquet de données contient des ressources moléculaires dérivées d'une vaste
      étude basée sur l'ADN de la biodiversité marine réalisée autour de l'île Calvert,
      en Colombie-Britannique, en 2021. Au cours de cette étude, nous avons prélevé
      trois échantillons d'eau de mer sur 208 sites répartis dans une région marine
      d'environ 100 km2, en nous concentrant sur les habitats côtiers de varech, d'herbiers
      marins et de récifs rocheux. Tous les échantillons ont été prélevés à proximité
      du substrat à l'aide d'une bouteille Niskin, filtrés à l'aide de filtres stérivexes
      de 0,22 μm, et l'ADN environnemental résultant a été utilisé pour le séquençage
      des amplicons afin de déduire les communautés de poissons (gène de l'ARNr 12S)
      et d'invertébrés (COI) à chaque endroit. Ces données s'inscrivent dans le cadre
      d'une collaboration plus large entre des chercheurs de l'Université McGill,
      de Pêches et Océans Canada et de l'Institut Hakai, dans le but d'optimiser l'utilisation
      de l'ADN environnemental pour surveiller le réseau d'aires marines protégées
      du Canada.
    translations:
      fr:
        message: text translated using the Amazon translate service / texte traduit
          à l'aide du service de traduction Amazon
        verified: false
  associated_resources: []
  dates:
    creation: '2021-09-01'
  edition: '1.0'
  identifier: https://doi.org/10.21966/vdyq-r660
  keywords:
    default:
      en:
      - marine protected areas
      - environmental DNA
      - biodiversity
      - fish
      fr:
      - poisson
    eov:
      en:
      - fishAbundanceAndDistribution
      - invertebrateAbundanceAndDistribution
      fr:
      - Abondance et distribution de poissons
      - Abondance et distribution d'invertébrés
  progress_code: completed
  project:
  - Genomics
  status: submitted
  temporal_begin: '2021-09-01T15:00:00.000Z'
  temporal_end: '2021-09-30T15:00:00.000Z'
  title:
    en: Environmental DNA survey of Calvert Island British Columbia, 2021
    fr: Étude d'ADN environnemental de l'île Calvert, Colombie-Britannique, 2021
    translations:
      fr:
        message: text translated using the Amazon translate service / texte traduit
          à l'aide du service de traduction Amazon
        verified: false
metadata:
  dates:
    revision: '2025-08-19T16:36:33.483Z'
  identifier: 7e9c97a3-4bf1-4852-81b6-d74cedf2c94c
  language: en
  maintenance_note: Generated from https://hakaiinstitute.github.io/hakai-metadata-entry-form#/en/hakai/pX9Euv7m4yaHRKPuMtylMexACtt2/-ORCQx4QHUuJ1NV1SEig
  naming_authority: ca.cioos
  use_constraints:
    licence:
      code: CC-BY-4.0
      title:
        en: Creative Commons Attribution 4.0 Attribution
      url: https://creativecommons.org/licenses/by/4.0
platform:
- id: small boat
  instruments: []
  type: surface vessel
spatial:
  bbox:
  - -128.6
  - 51.31
  - -127.3
  - 52.05
  description:
    en: Nearshore habitats of kelp, seagrass, and rocky reefs
    fr: Habitats côtiers de varech, d'herbiers marins et de récifs rocheux
    translations:
      fr:
        message: text translated using the Amazon translate service / texte traduit
          à l'aide du service de traduction Amazon
        verified: false
  vertical:
  - 0.0
  - 60.0
  vertical_positive: heightPositive
