name: Links

on:
#   repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 00 1 * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write # required for peter-evans/create-issue-from-file
      contents: write # required for JamesIves/github-pages-deploy-action
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
            # Check all markdown, html and reStructuredText files in repo (default)
            # ignore certificate errors
            args: >-
              --base . 
              --verbose 
              --no-progress
              --cache
              --max-retries 1
              --timeout 1000
              --method head
              --user-agent 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36'
              --insecure
              --exclude-path unpublished
              --exclude-path iys
              --accept 100..=103,200..=299,304,418,403
              --max-concurrency 1
              './**/*.xml'
            # Use json as output format (instead of markdown)
            format: markdown
            # # Use a custom GitHub token, which
            # token: ${{ secrets.CUSTOM_TOKEN }}
            # Don't fail action on broken links, set to true to block pr's on failed links
            fail: false

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # install the python version needed

      - name: Add metadata form link to report
        run: |
          python add_form_url_to_link_check_report.py

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0 && github.event_name != 'workflow_dispatch'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
          assignees: timvdstap
          
      # publish the link check report to github pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: lychee
          clean: true
          clean-exclude: |
            _config.yml
            /assets/css/style.scss